using Newtonsoft.Json.Linq;

namespace osc_sdk_csharp.src.Enums;
public class Banks
{
    private static KeyValuePair<string, string> CreateBanks(string key)
    {
        IDictionary<string, string> banks = new Dictionary<string, string>( );
        banks.Add("001", "BANCO DO BRASIL S.A.");
        banks.Add("003", "BANCO DA AMAZONIA S.A.");
        banks.Add("004", "BANCO DO NORDESTE DO BRASIL S.A.");
        banks.Add("007", "BNDES");
        banks.Add("010", "CREDICOAMO");
        banks.Add("011", "C.SUISSE HEDGING-GRIFFO CV S/A");
        banks.Add("012", "BANCO INBURSA");
        banks.Add("014", "STATE STREET BR S.A. BCO COMERCIAL");
        banks.Add("015", "UBS BRASIL CCTVM S.A.");
        banks.Add("016", "SICOOB CREDITRAN");
        banks.Add("017", "BNY MELLON BCO S.A.");
        banks.Add("018", "BCO TRICURY S.A.");
        banks.Add("021", "BCO BANESTES S.A.");
        banks.Add("024", "BCO BANDEPE S.A.");
        banks.Add("025", "BCO ALFA S.A.");
        banks.Add("029", "BANCO ITAÚ CONSIGNADO S.A.");
        banks.Add("033", "BANCO SANTANDER (BRASIL) S. A.");
        banks.Add("036", "BCO BBI S.A.");
        banks.Add("037", "BCO DO EST. DO PA S.A.");
        banks.Add("040", "BCO CARGILL S.A.");
        banks.Add("041", "BCO DO ESTADO DO RS S.A.");
        banks.Add("047", "BCO DO EST. DE SE S.A.");
        banks.Add("060", "CONFIDENCE CC S.A.");
        banks.Add("062", "HIPERCARD BM S.A.");
        banks.Add("063", "BANCO BRADESCARD");
        banks.Add("064", "GOLDMAN SACHS DO BRASIL BM S.A");
        banks.Add("065", "BCO ANDBANK S.A.");
        banks.Add("066", "BCO MORGAN STANLEY S.A.");
        banks.Add("069", "BCO CREFISA S.A.");
        banks.Add("070", "BRB - BCO DE BRASILIA S.A.");
        banks.Add("074", "BCO. J.SAFRA S.A.");
        banks.Add("075", "BCO ABN AMRO S.A.");
        banks.Add("076", "BCO KDB BRASIL S.A.");
        banks.Add("077", "BANCO INTER");
        banks.Add("078", "HAITONG BI DO BRASIL S.A.");
        banks.Add("079", "BCO ORIGINAL DO AGRO S/A");
        banks.Add("080", "B&T CC LTDA.");
        banks.Add("081", "BANCOSEGURO S.A.");
        banks.Add("082", "BANCO TOPÁZIO S.A.");
        banks.Add("083", "BCO DA CHINA BRASIL S.A.");
        banks.Add("084", "UNIPRIME NORTE DO PARANÁ - CC");
        banks.Add("085", "COOP CENTRAL AILOS");
        banks.Add("089", "CREDISAN CC");
        banks.Add("091", "CCCM UNICRED CENTRAL RS");
        banks.Add("092", "BRK S.A. CFI");
        banks.Add("093", "POLOCRED SCMEPP LTDA.");
        banks.Add("094", "BANCO FINAXIS");
        banks.Add("095", "TRAVELEX BANCO DE CÂMBIO S.A.");
        banks.Add("096", "BCO B3 S.A.");
        banks.Add("097", "CREDISIS CENTRAL DE COOPERATIVAS DE CRÉDITO LTDA.");
        banks.Add("098", "CREDIALIANÇA CCR");
        banks.Add("099", "UNIPRIME CENTRAL CCC LTDA.");
        banks.Add("100", "PLANNER CV S.A.");
        banks.Add("101", "RENASCENCA DTVM LTDA");
        banks.Add("102", "XP INVESTIMENTOS CCTVM S/A");
        banks.Add("104", "CAIXA ECONÔMICA FEDERAL");
        banks.Add("105", "LECCA CFI S.A.");
        banks.Add("107", "BCO BOCOM BBM S.A.");
        banks.Add("108", "PORTOCRED S.A. - CFI");
        banks.Add("111", "OLIVEIRA TRUST DTVM S.A.");
        banks.Add("113", "MAGLIANO S.A. CCVM");
        banks.Add("114", "CENTRAL COOPERATIVA DE CRÉDITO NO ESTADO DO ESPÍRITO SANTO");
        banks.Add("117", "ADVANCED CC LTDA");
        banks.Add("119", "BCO WESTERN UNION");
        banks.Add("120", "BCO RODOBENS S.A.");
        banks.Add("121", "BCO AGIBANK S.A.");
        banks.Add("122", "BCO BRADESCO BERJ S.A.");
        banks.Add("124", "BCO WOORI BANK DO BRASIL S.A.");
        banks.Add("125", "PLURAL BCO BM");
        banks.Add("126", "BR PARTNERS BI");
        banks.Add("127", "CODEPE CVC S.A.");
        banks.Add("128", "MS BANK S.A. BCO DE CÂMBIO");
        banks.Add("129", "UBS BRASIL BI S.A.");
        banks.Add("130", "CARUANA SCFI");
        banks.Add("131", "TULLETT PREBON BRASIL CVC LTDA");
        banks.Add("132", "ICBC DO BRASIL BM S.A.");
        banks.Add("133", "CRESOL CONFEDERAÇÃO");
        banks.Add("134", "BGC LIQUIDEZ DTVM LTDA");
        banks.Add("136", "UNICRED");
        banks.Add("138", "GET MONEY CC LTDA");
        banks.Add("139", "INTESA SANPAOLO BRASIL S.A. BM");
        banks.Add("140", "EASYNVEST - TÍTULO CV SA");
        banks.Add("142", "BROKER BRASIL CC LTDA.");
        banks.Add("143", "TREVISO CC S.A.");
        banks.Add("144", "BEXS BCO DE CAMBIO S.A.");
        banks.Add("145", "LEVYCAM CCV LTDA");
        banks.Add("146", "GUITTA CC LTDA");
        banks.Add("149", "FACTA S.A. CFI");
        banks.Add("157", "ICAP DO BRASIL CTVM LTDA.");
        banks.Add("159", "CASA CREDITO S.A. SCM");
        banks.Add("163", "COMMERZBANK BRASIL S.A. - BCO MÚLTIPLO");
        banks.Add("169", "BCO OLÉ BONSUCESSO CONSIGNADO S.A.");
        banks.Add("173", "BRL TRUST DTVM SA");
        banks.Add("174", "PERNAMBUCANAS FINANC S.A. CFI");
        banks.Add("177", "GUIDE");
        banks.Add("180", "CM CAPITAL MARKETS CCTVM LTDA");
        banks.Add("183", "SOCRED SA - SCMEPP");
        banks.Add("184", "BCO ITAÚ BBA S.A.");
        banks.Add("188", "ATIVA S.A. INVESTIMENTOS CCTVM");
        banks.Add("189", "HS FINANCEIRA");
        banks.Add("190", "SERVICOOP");
        banks.Add("191", "NOVA FUTURA CTVM LTDA.");
        banks.Add("194", "PARMETAL DTVM LTDA");
        banks.Add("196", "FAIR CC S.A.");
        banks.Add("197", "STONE PAGAMENTOS S.A.");
        banks.Add("208", "BANCO BTG PACTUAL S.A.");
        banks.Add("212", "BANCO ORIGINAL");
        banks.Add("213", "BCO ARBI S.A.");
        banks.Add("217", "BANCO JOHN DEERE S.A.");
        banks.Add("218", "BCO BS2 S.A.");
        banks.Add("222", "BCO CRÉDIT AGRICOLE BR S.A.");
        banks.Add("224", "BCO FIBRA S.A.");
        banks.Add("233", "BANCO CIFRA");
        banks.Add("237", "BANCO BRADESCO S.A.");
        banks.Add("241", "BCO CLASSICO S.A.");
        banks.Add("243", "BCO MÁXIMA S.A.");
        banks.Add("246", "BCO ABC BRASIL S.A.");
        banks.Add("249", "BANCO INVESTCRED UNIBANCO S.A.");
        banks.Add("250", "BCV");
        banks.Add("253", "BEXS CC S.A.");
        banks.Add("254", "PARANA BCO S.A.");
        banks.Add("259", "MONEYCORP BCO DE CÂMBIO S.A.");
        banks.Add("260", "NU PAGAMENTOS S.A.");
        banks.Add("265", "BCO FATOR S.A.");
        banks.Add("266", "BCO CEDULA S.A.");
        banks.Add("268", "BARI CIA HIPOTECÁRIA");
        banks.Add("269", "HSBC BANCO DE INVESTIMENTO");
        banks.Add("270", "SAGITUR CC LTDA");
        banks.Add("271", "IB CCTVM S.A.");
        banks.Add("272", "AGK CC S.A.");
        banks.Add("273", "CCR DE SÃO MIGUEL DO OESTE");
        banks.Add("274", "MONEY PLUS SCMEPP LTDA");
        banks.Add("276", "SENFF S.A. - CFI");
        banks.Add("278", "GENIAL INVESTIMENTOS CVM S.A.");
        banks.Add("279", "CCR DE PRIMAVERA DO LESTE");
        banks.Add("280", "AVISTA S.A. CFI");
        banks.Add("281", "CCR COOPAVEL");
        banks.Add("283", "RB CAPITAL INVESTIMENTOS DTVM LTDA.");
        banks.Add("285", "FRENTE CC LTDA.");
        banks.Add("286", "CCR DE OURO");
        banks.Add("288", "CAROL DTVM LTDA.");
        banks.Add("289", "DECYSEO CC LTDA.");
        banks.Add("290", "PAGSEGURO");
        banks.Add("292", "BS2 DTVM S.A.");
        banks.Add("293", "LASTRO RDV DTVM LTDA");
        banks.Add("296", "VISION S.A. CC");
        banks.Add("298", "VIPS CC LTDA.");
        banks.Add("299", "SOROCRED CFI S.A.");
        banks.Add("300", "BCO LA NACION ARGENTINA");
        banks.Add("301", "BPP IP S.A.");
        banks.Add("306", "PORTOPAR DTVM LTDA");
        banks.Add("307", "TERRA INVESTIMENTOS DTVM");
        banks.Add("309", "CAMBIONET CC LTDA");
        banks.Add("310", "VORTX DTVM LTDA.");
        banks.Add("315", "PI DTVM S.A.");
        banks.Add("318", "BCO BMG S.A.");
        banks.Add("319", "OM DTVM LTDA");
        banks.Add("320", "BCO CCB BRASIL S.A.");
        banks.Add("321", "CREFAZ SCMEPP LTDA");
        banks.Add("322", "CCR DE ABELARDO LUZ");
        banks.Add("323", "MERCADO PAGO");
        banks.Add("325", "ÓRAMA DTVM S.A.");
        banks.Add("326", "PARATI - CFI S.A.");
        banks.Add("329", "QI SCD S.A.");
        banks.Add("330", "BANCO BARI S.A.");
        banks.Add("331", "FRAM CAPITAL DTVM S.A.");
        banks.Add("332", "ACESSO");
        banks.Add("335", "BANCO DIGIO");
        banks.Add("336", "BCO C6 S.A.");
        banks.Add("340", "SUPER PAGAMENTOS E ADMINISTRACAO DE MEIOS ELETRONICOS S.A.");
        banks.Add("341", "ITAÚ UNIBANCO  S.A.");
        banks.Add("342", "CREDITAS SCD");
        banks.Add("343", "FFA SCMEPP LTDA.");
        banks.Add("348", "BCO XP S.A.");
        banks.Add("349", "AMAGGI S.A. CFI");
        banks.Add("352", "TORO CTVM LTDA");
        banks.Add("354", "NECTON INVESTIMENTOS S.A CVM");
        banks.Add("355", "ÓTIMO SCD S.A.");
        banks.Add("364", "GERENCIANET PAGTOS BRASIL LTDA");
        banks.Add("365", "SOLIDUS S.A. CCVM");
        banks.Add("366", "BCO SOCIETE GENERALE BRASIL");
        banks.Add("367", "VITREO DTVM S.A.");
        banks.Add("370", "BCO MIZUHO S.A.");
        banks.Add("373", "UP.P SEP S.A.");
        banks.Add("376", "BCO J.P. MORGAN S.A.");
        banks.Add("389", "BCO MERCANTIL DO BRASIL S.A.");
        banks.Add("394", "BCO BRADESCO FINANC. S.A.");
        banks.Add("399", "KIRTON BANK");
        banks.Add("412", "BCO CAPITAL S.A.");
        banks.Add("413", "BCO BV S.A.");
        banks.Add("422", "BCO SAFRA S.A.");
        banks.Add("450", "FITBANK PAGAMENTOS ELETRONICOS S.A.");
        banks.Add("456", "BCO MUFG BRASIL S.A.");
        banks.Add("464", "BCO SUMITOMO MITSUI BRASIL S.A.");
        banks.Add("473", "BCO CAIXA GERAL BRASIL S.A.");
        banks.Add("477", "CITIBANK N.A.");
        banks.Add("479", "BCO ITAUBANK S.A.");
        banks.Add("487", "DEUTSCHE BANK S.A.BCO ALEMAO");
        banks.Add("488", "JPMORGAN CHASE BANK");
        banks.Add("492", "ING BANK N.V.");
        banks.Add("495", "BCO LA PROVINCIA B AIRES BCE");
        banks.Add("505", "BCO CREDIT SUISSE S.A.");
        banks.Add("545", "SENSO CCVM S.A.");
        banks.Add("600", "BCO LUSO BRASILEIRO S.A.");
        banks.Add("604", "BCO INDUSTRIAL DO BRASIL S.A.");
        banks.Add("610", "BCO VR S.A.");
        banks.Add("611", "BCO PAULISTA S.A.");
        banks.Add("612", "BCO GUANABARA S.A.");
        banks.Add("613", "OMNI BANCO S.A.");
        banks.Add("623", "BANCO PAN");
        banks.Add("626", "BCO FICSA S.A.");
        banks.Add("630", "SMARTBANK");
        banks.Add("633", "BCO RENDIMENTO S.A.");
        banks.Add("634", "BCO TRIANGULO S.A.");
        banks.Add("637", "BCO SOFISA S.A.");
        banks.Add("643", "BCO PINE S.A.");
        banks.Add("652", "ITAÚ UNIBANCO HOLDING S.A.");
        banks.Add("653", "BCO INDUSVAL S.A.");
        banks.Add("654", "BCO A.J. RENNER S.A.");
        banks.Add("707", "BCO DAYCOVAL S.A");
        banks.Add("712", "BCO OURINVEST S.A.");
        banks.Add("735", "BANCO NEON");
        banks.Add("739", "BCO CETELEM S.A.");
        banks.Add("741", "BCO RIBEIRAO PRETO S.A.");
        banks.Add("743", "BANCO SEMEAR");
        banks.Add("745", "BCO CITIBANK S.A.");
        banks.Add("746", "BCO MODAL S.A.");
        banks.Add("747", "BCO RABOBANK INTL BRASIL S.A.");
        banks.Add("748", "BCO COOPERATIVO SICREDI S.A.");
        banks.Add("751", "SCOTIABANK BRASIL");
        banks.Add("752", "BCO BNP PARIBAS BRASIL S A");
        banks.Add("753", "NOVO BCO CONTINENTAL S.A. - BM");
        banks.Add("754", "BANCO SISTEMA");
        banks.Add("755", "BOFA MERRILL LYNCH BM S.A.");
        banks.Add("756", "BANCOOB");
        banks.Add("757", "BCO KEB HANA DO BRASIL S.A.");
        banks.Add("34878543", "Claro Pay S.A.");

        if(string.IsNullOrEmpty(key) || !banks.ContainsKey(key))
            throw new ArgumentNullException("Banco inexistente!");

        return banks.SingleOrDefault(p => p.Key == key);
    }
    public static string GetName(string key)
    {
        var Bank = CreateBanks(key);

        return Bank.Value;
    }
}
